// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notification/notification.proto

package notification

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Id                      int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationName        string   `protobuf:"bytes,2,opt,name=organizationName,proto3" json:"organizationName,omitempty"`
	OrganizationId          int64    `protobuf:"varint,3,opt,name=organizationId,proto3" json:"organizationId,omitempty"`
	ApplicationName         string   `protobuf:"bytes,4,opt,name=applicationName,proto3" json:"applicationName,omitempty"`
	ApplicationId           int64    `protobuf:"varint,5,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
	EnvironmentName         string   `protobuf:"bytes,6,opt,name=environmentName,proto3" json:"environmentName,omitempty"`
	EnvironmentId           int64    `protobuf:"varint,7,opt,name=environmentId,proto3" json:"environmentId,omitempty"`
	EnvironmentResourceName string   `protobuf:"bytes,8,opt,name=environmentResourceName,proto3" json:"environmentResourceName,omitempty"`
	EnvironmentResourceId   int64    `protobuf:"varint,9,opt,name=environmentResourceId,proto3" json:"environmentResourceId,omitempty"`
	ProjectName             string   `protobuf:"bytes,10,opt,name=projectName,proto3" json:"projectName,omitempty"`
	ProjectId               int64    `protobuf:"varint,11,opt,name=projectId,proto3" json:"projectId,omitempty"`
	Type                    string   `protobuf:"bytes,12,opt,name=type,proto3" json:"type,omitempty"`
	Body                    string   `protobuf:"bytes,13,opt,name=body,proto3" json:"body,omitempty"`
	SendBy                  string   `protobuf:"bytes,14,opt,name=sendBy,proto3" json:"sendBy,omitempty"`
	Scope                   string   `protobuf:"bytes,15,opt,name=scope,proto3" json:"scope,omitempty"`
	ScopeId                 int64    `protobuf:"varint,16,opt,name=scopeId,proto3" json:"scopeId,omitempty"`
	Action                  string   `protobuf:"bytes,17,opt,name=action,proto3" json:"action,omitempty"`
	User                    int64    `protobuf:"varint,18,opt,name=user,proto3" json:"user,omitempty"`
	UserName                string   `protobuf:"bytes,19,opt,name=userName,proto3" json:"userName,omitempty"`
	TriggeredBy             int64    `protobuf:"varint,20,opt,name=triggeredBy,proto3" json:"triggeredBy,omitempty"`
	TriggeredByName         string   `protobuf:"bytes,21,opt,name=triggeredByName,proto3" json:"triggeredByName,omitempty"`
	Seen                    bool     `protobuf:"varint,22,opt,name=seen,proto3" json:"seen,omitempty"`
	CreateTimestamp         int64    `protobuf:"varint,23,opt,name=createTimestamp,proto3" json:"createTimestamp,omitempty"`
	UpdateTimestamp         int64    `protobuf:"varint,24,opt,name=updateTimestamp,proto3" json:"updateTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff76f27cb6af8e56, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetOrganizationName() string {
	if m != nil {
		return m.OrganizationName
	}
	return ""
}

func (m *Message) GetOrganizationId() int64 {
	if m != nil {
		return m.OrganizationId
	}
	return 0
}

func (m *Message) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *Message) GetApplicationId() int64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *Message) GetEnvironmentName() string {
	if m != nil {
		return m.EnvironmentName
	}
	return ""
}

func (m *Message) GetEnvironmentId() int64 {
	if m != nil {
		return m.EnvironmentId
	}
	return 0
}

func (m *Message) GetEnvironmentResourceName() string {
	if m != nil {
		return m.EnvironmentResourceName
	}
	return ""
}

func (m *Message) GetEnvironmentResourceId() int64 {
	if m != nil {
		return m.EnvironmentResourceId
	}
	return 0
}

func (m *Message) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *Message) GetProjectId() int64 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *Message) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Message) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Message) GetSendBy() string {
	if m != nil {
		return m.SendBy
	}
	return ""
}

func (m *Message) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *Message) GetScopeId() int64 {
	if m != nil {
		return m.ScopeId
	}
	return 0
}

func (m *Message) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Message) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *Message) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Message) GetTriggeredBy() int64 {
	if m != nil {
		return m.TriggeredBy
	}
	return 0
}

func (m *Message) GetTriggeredByName() string {
	if m != nil {
		return m.TriggeredByName
	}
	return ""
}

func (m *Message) GetSeen() bool {
	if m != nil {
		return m.Seen
	}
	return false
}

func (m *Message) GetCreateTimestamp() int64 {
	if m != nil {
		return m.CreateTimestamp
	}
	return 0
}

func (m *Message) GetUpdateTimestamp() int64 {
	if m != nil {
		return m.UpdateTimestamp
	}
	return 0
}

type QueryRequest struct {
	User                 int64    `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Filter               string   `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff76f27cb6af8e56, []int{1}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *QueryRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *QueryRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *QueryRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *QueryRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

type EmailMessage struct {
	User                 []string `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	Subject              string   `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Link                 string   `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	Caption              string   `protobuf:"bytes,5,opt,name=caption,proto3" json:"caption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailMessage) Reset()         { *m = EmailMessage{} }
func (m *EmailMessage) String() string { return proto.CompactTextString(m) }
func (*EmailMessage) ProtoMessage()    {}
func (*EmailMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff76f27cb6af8e56, []int{2}
}

func (m *EmailMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailMessage.Unmarshal(m, b)
}
func (m *EmailMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailMessage.Marshal(b, m, deterministic)
}
func (m *EmailMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailMessage.Merge(m, src)
}
func (m *EmailMessage) XXX_Size() int {
	return xxx_messageInfo_EmailMessage.Size(m)
}
func (m *EmailMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EmailMessage proto.InternalMessageInfo

func (m *EmailMessage) GetUser() []string {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *EmailMessage) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *EmailMessage) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *EmailMessage) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *EmailMessage) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

type QueryResponse struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff76f27cb6af8e56, []int{3}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type PostRequest struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostRequest) Reset()         { *m = PostRequest{} }
func (m *PostRequest) String() string { return proto.CompactTextString(m) }
func (*PostRequest) ProtoMessage()    {}
func (*PostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff76f27cb6af8e56, []int{4}
}

func (m *PostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostRequest.Unmarshal(m, b)
}
func (m *PostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostRequest.Marshal(b, m, deterministic)
}
func (m *PostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostRequest.Merge(m, src)
}
func (m *PostRequest) XXX_Size() int {
	return xxx_messageInfo_PostRequest.Size(m)
}
func (m *PostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostRequest proto.InternalMessageInfo

func (m *PostRequest) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type PostResponse struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostResponse) Reset()         { *m = PostResponse{} }
func (m *PostResponse) String() string { return proto.CompactTextString(m) }
func (*PostResponse) ProtoMessage()    {}
func (*PostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff76f27cb6af8e56, []int{5}
}

func (m *PostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResponse.Unmarshal(m, b)
}
func (m *PostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResponse.Marshal(b, m, deterministic)
}
func (m *PostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResponse.Merge(m, src)
}
func (m *PostResponse) XXX_Size() int {
	return xxx_messageInfo_PostResponse.Size(m)
}
func (m *PostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostResponse proto.InternalMessageInfo

func (m *PostResponse) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type UpdateRequest struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff76f27cb6af8e56, []int{6}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type UpdateResponse struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff76f27cb6af8e56, []int{7}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type DeleteRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff76f27cb6af8e56, []int{8}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteResponse struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff76f27cb6af8e56, []int{9}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type MarkAllRequest struct {
	User                 int64    `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Type                 int64    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarkAllRequest) Reset()         { *m = MarkAllRequest{} }
func (m *MarkAllRequest) String() string { return proto.CompactTextString(m) }
func (*MarkAllRequest) ProtoMessage()    {}
func (*MarkAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff76f27cb6af8e56, []int{10}
}

func (m *MarkAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkAllRequest.Unmarshal(m, b)
}
func (m *MarkAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkAllRequest.Marshal(b, m, deterministic)
}
func (m *MarkAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkAllRequest.Merge(m, src)
}
func (m *MarkAllRequest) XXX_Size() int {
	return xxx_messageInfo_MarkAllRequest.Size(m)
}
func (m *MarkAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MarkAllRequest proto.InternalMessageInfo

func (m *MarkAllRequest) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *MarkAllRequest) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

type MarkAllResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarkAllResponse) Reset()         { *m = MarkAllResponse{} }
func (m *MarkAllResponse) String() string { return proto.CompactTextString(m) }
func (*MarkAllResponse) ProtoMessage()    {}
func (*MarkAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff76f27cb6af8e56, []int{11}
}

func (m *MarkAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkAllResponse.Unmarshal(m, b)
}
func (m *MarkAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkAllResponse.Marshal(b, m, deterministic)
}
func (m *MarkAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkAllResponse.Merge(m, src)
}
func (m *MarkAllResponse) XXX_Size() int {
	return xxx_messageInfo_MarkAllResponse.Size(m)
}
func (m *MarkAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MarkAllResponse proto.InternalMessageInfo

func (m *MarkAllResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SendEmailRequest struct {
	Message              *EmailMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SendEmailRequest) Reset()         { *m = SendEmailRequest{} }
func (m *SendEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendEmailRequest) ProtoMessage()    {}
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff76f27cb6af8e56, []int{12}
}

func (m *SendEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailRequest.Unmarshal(m, b)
}
func (m *SendEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailRequest.Merge(m, src)
}
func (m *SendEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendEmailRequest.Size(m)
}
func (m *SendEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailRequest proto.InternalMessageInfo

func (m *SendEmailRequest) GetMessage() *EmailMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

type SendEmailResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailResponse) Reset()         { *m = SendEmailResponse{} }
func (m *SendEmailResponse) String() string { return proto.CompactTextString(m) }
func (*SendEmailResponse) ProtoMessage()    {}
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff76f27cb6af8e56, []int{13}
}

func (m *SendEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailResponse.Unmarshal(m, b)
}
func (m *SendEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailResponse.Marshal(b, m, deterministic)
}
func (m *SendEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailResponse.Merge(m, src)
}
func (m *SendEmailResponse) XXX_Size() int {
	return xxx_messageInfo_SendEmailResponse.Size(m)
}
func (m *SendEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailResponse proto.InternalMessageInfo

func (m *SendEmailResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Message)(nil), "notification.Message")
	proto.RegisterType((*QueryRequest)(nil), "notification.QueryRequest")
	proto.RegisterType((*EmailMessage)(nil), "notification.EmailMessage")
	proto.RegisterType((*QueryResponse)(nil), "notification.QueryResponse")
	proto.RegisterType((*PostRequest)(nil), "notification.PostRequest")
	proto.RegisterType((*PostResponse)(nil), "notification.PostResponse")
	proto.RegisterType((*UpdateRequest)(nil), "notification.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "notification.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "notification.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "notification.DeleteResponse")
	proto.RegisterType((*MarkAllRequest)(nil), "notification.MarkAllRequest")
	proto.RegisterType((*MarkAllResponse)(nil), "notification.MarkAllResponse")
	proto.RegisterType((*SendEmailRequest)(nil), "notification.SendEmailRequest")
	proto.RegisterType((*SendEmailResponse)(nil), "notification.SendEmailResponse")
}

func init() { proto.RegisterFile("notification/notification.proto", fileDescriptor_ff76f27cb6af8e56) }

var fileDescriptor_ff76f27cb6af8e56 = []byte{
	// 780 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x6d, 0x9a, 0x34, 0x3f, 0x93, 0x9f, 0xb6, 0xfb, 0xb5, 0xe9, 0x7e, 0xa6, 0xd0, 0xc8, 0x42,
	0x28, 0x02, 0xd1, 0x8a, 0xd2, 0x8b, 0x5e, 0x51, 0x1a, 0x51, 0xa9, 0xb9, 0x68, 0x55, 0x0c, 0x3c,
	0x80, 0x63, 0x6f, 0xc2, 0x52, 0xc7, 0x36, 0x5e, 0x07, 0x29, 0x08, 0xf1, 0x3e, 0x3c, 0x25, 0x68,
	0x67, 0x6d, 0x67, 0x6d, 0x12, 0x10, 0xb9, 0xca, 0xce, 0x99, 0xd9, 0x73, 0x66, 0x77, 0xce, 0x5a,
	0x81, 0x23, 0x3f, 0x88, 0xf9, 0x98, 0x3b, 0x76, 0xcc, 0x03, 0xff, 0x44, 0x0f, 0x8e, 0xc3, 0x28,
	0x88, 0x03, 0xd2, 0xd2, 0x31, 0xf3, 0x47, 0x15, 0x6a, 0x37, 0x4c, 0x08, 0x7b, 0xc2, 0x48, 0x07,
	0x36, 0xb9, 0x4b, 0x4b, 0xbd, 0x52, 0xbf, 0x6c, 0x6d, 0x72, 0x97, 0x3c, 0x85, 0x9d, 0x20, 0x9a,
	0xd8, 0x3e, 0xff, 0x8a, 0xb5, 0xb7, 0xf6, 0x94, 0xd1, 0xcd, 0x5e, 0xa9, 0xdf, 0xb0, 0x7e, 0xc3,
	0xc9, 0x13, 0xe8, 0xe8, 0xd8, 0xd0, 0xa5, 0x65, 0xe4, 0x29, 0xa0, 0xa4, 0x0f, 0xdb, 0x76, 0x18,
	0x7a, 0x89, 0x3c, 0x52, 0x56, 0x90, 0xb2, 0x08, 0x93, 0xc7, 0xd0, 0xd6, 0xa0, 0xa1, 0x4b, 0xb7,
	0x90, 0x30, 0x0f, 0x4a, 0x3e, 0xe6, 0x7f, 0xe1, 0x51, 0xe0, 0x4f, 0x99, 0x1f, 0x23, 0x5f, 0x55,
	0xf1, 0x15, 0x60, 0xc9, 0xa7, 0x41, 0x43, 0x97, 0xd6, 0x14, 0x5f, 0x0e, 0x24, 0xe7, 0x70, 0xa0,
	0x01, 0x16, 0x13, 0xc1, 0x2c, 0x72, 0x18, 0xf2, 0xd6, 0x91, 0x77, 0x55, 0x9a, 0x9c, 0xc1, 0xfe,
	0x92, 0xd4, 0xd0, 0xa5, 0x0d, 0xd4, 0x59, 0x9e, 0x24, 0x3d, 0x68, 0x86, 0x51, 0xf0, 0x89, 0x39,
	0xaa, 0x77, 0x40, 0x0d, 0x1d, 0x22, 0x87, 0xd0, 0x48, 0xc2, 0xa1, 0x4b, 0x9b, 0xc8, 0xb5, 0x00,
	0x08, 0x81, 0x4a, 0x3c, 0x0f, 0x19, 0x6d, 0xe1, 0x46, 0x5c, 0x4b, 0x6c, 0x14, 0xb8, 0x73, 0xda,
	0x56, 0x98, 0x5c, 0x93, 0x2e, 0x54, 0x05, 0xf3, 0xdd, 0xc1, 0x9c, 0x76, 0x10, 0x4d, 0x22, 0xb2,
	0x07, 0x5b, 0xc2, 0x09, 0x42, 0x46, 0xb7, 0x11, 0x56, 0x01, 0xa1, 0x50, 0xc3, 0xc5, 0xd0, 0xa5,
	0x3b, 0xa8, 0x98, 0x86, 0x92, 0xc7, 0x76, 0xe4, 0xdd, 0xd3, 0x5d, 0xc5, 0xa3, 0x22, 0xa9, 0x39,
	0x13, 0x2c, 0xa2, 0x04, 0xcb, 0x71, 0x4d, 0x0c, 0xa8, 0xcb, 0x5f, 0x3c, 0xd8, 0x7f, 0x58, 0x9d,
	0xc5, 0xf2, 0xdc, 0x71, 0xc4, 0x27, 0x13, 0x16, 0x31, 0xd9, 0xd4, 0x1e, 0x6e, 0xd3, 0x21, 0x39,
	0x59, 0x2d, 0x44, 0x92, 0x7d, 0x35, 0xd9, 0x02, 0x2c, 0xb5, 0x05, 0x63, 0x3e, 0xed, 0xf6, 0x4a,
	0xfd, 0xba, 0x85, 0x6b, 0xb9, 0xdb, 0x89, 0x98, 0x1d, 0xb3, 0xf7, 0x7c, 0xca, 0x44, 0x6c, 0x4f,
	0x43, 0x7a, 0x80, 0x1a, 0x45, 0x58, 0x56, 0xce, 0x42, 0x37, 0x57, 0x49, 0x55, 0x65, 0x01, 0x36,
	0xbf, 0x41, 0xeb, 0xed, 0x8c, 0x45, 0x73, 0x8b, 0x7d, 0x9e, 0x31, 0x11, 0x67, 0x67, 0x2e, 0x69,
	0x67, 0xee, 0x42, 0x35, 0x18, 0x8f, 0x05, 0x8b, 0xf1, 0xa5, 0x94, 0xad, 0x24, 0x92, 0xf7, 0xec,
	0xf1, 0x29, 0x8f, 0x93, 0x67, 0xa1, 0x82, 0x6c, 0x7a, 0x15, 0x6d, 0x7a, 0x5d, 0xa8, 0x8e, 0xb9,
	0x17, 0xb3, 0x08, 0x0d, 0xdf, 0xb0, 0x92, 0xc8, 0xfc, 0x0e, 0xad, 0xab, 0xa9, 0xcd, 0xbd, 0xf4,
	0xb5, 0x2e, 0xd4, 0xcb, 0x72, 0x2f, 0xaa, 0xcb, 0xb9, 0xcd, 0x46, 0xd2, 0x1a, 0xc9, 0x43, 0x4d,
	0xc3, 0xcc, 0x13, 0x65, 0xcd, 0x13, 0x04, 0x2a, 0x1e, 0xf7, 0xef, 0x53, 0x75, 0xb9, 0x96, 0x0c,
	0x8e, 0x1d, 0xe2, 0x80, 0x95, 0x7c, 0x1a, 0x9a, 0x03, 0x68, 0x27, 0xa7, 0x17, 0x61, 0xe0, 0x0b,
	0x46, 0x5e, 0x40, 0x7d, 0xaa, 0x7a, 0x11, 0xd8, 0x44, 0xf3, 0x74, 0xff, 0x38, 0xf7, 0xbd, 0x49,
	0x3a, 0xb5, 0xb2, 0x32, 0xf3, 0x15, 0x34, 0xef, 0x02, 0x11, 0xa7, 0x17, 0x78, 0x02, 0xb5, 0x24,
	0x85, 0x77, 0xb8, 0x92, 0x20, 0xad, 0x32, 0x2f, 0xa0, 0xa5, 0xf6, 0x27, 0x2d, 0xfc, 0x33, 0xc1,
	0x6b, 0x68, 0x7f, 0xc0, 0xa9, 0xae, 0xdd, 0xc2, 0x25, 0x74, 0x52, 0x86, 0x75, 0x9b, 0x38, 0x82,
	0xf6, 0x1b, 0xe6, 0xb1, 0x45, 0x13, 0x85, 0x0f, 0xaf, 0xd4, 0x48, 0x0b, 0xd6, 0xd5, 0x38, 0x87,
	0xce, 0x8d, 0x1d, 0xdd, 0x5f, 0x7a, 0xde, 0x9f, 0xdc, 0x9a, 0xfa, 0x4f, 0x79, 0x15, 0xd7, 0xe6,
	0x33, 0xd8, 0xce, 0x76, 0x26, 0xea, 0x68, 0x2b, 0xc7, 0x61, 0x42, 0xe0, 0xee, 0xba, 0x95, 0x86,
	0xe6, 0x35, 0xec, 0xbc, 0x63, 0xbe, 0x8b, 0xc6, 0x4c, 0x85, 0xce, 0x8a, 0xbd, 0x1a, 0xf9, 0x5e,
	0x75, 0x17, 0x2f, 0x1a, 0x7e, 0x0e, 0xbb, 0x1a, 0xd3, 0xdf, 0x84, 0x4f, 0x7f, 0x96, 0xa1, 0x75,
	0xab, 0xb1, 0x92, 0x01, 0xd4, 0xee, 0x66, 0x23, 0x8f, 0x8b, 0x8f, 0xe4, 0xff, 0xbc, 0x9e, 0xe6,
	0x38, 0xc3, 0x58, 0x96, 0x52, 0x62, 0xe6, 0x06, 0xb9, 0x80, 0x8a, 0x44, 0xd6, 0x27, 0x18, 0xc0,
	0x16, 0xbe, 0x11, 0x52, 0x28, 0xd3, 0x3f, 0x1b, 0xc6, 0x83, 0xa5, 0xb9, 0x8c, 0xe3, 0x0a, 0xaa,
	0xca, 0x60, 0xa4, 0x50, 0x98, 0x33, 0xae, 0x71, 0xb8, 0x3c, 0x99, 0xd1, 0x5c, 0x43, 0x2d, 0x19,
	0x23, 0x29, 0x94, 0xe6, 0x7d, 0x61, 0x3c, 0x5c, 0x91, 0xd5, 0x1b, 0x52, 0x6e, 0x2c, 0x36, 0x94,
	0x33, 0x71, 0xb1, 0xa1, 0xbc, 0x81, 0xcd, 0x0d, 0x72, 0x0b, 0x8d, 0x6c, 0xc0, 0xe4, 0x51, 0xbe,
	0xb8, 0xe8, 0x21, 0xe3, 0x68, 0x65, 0x3e, 0xe5, 0x1b, 0x55, 0xf1, 0xef, 0xcc, 0xcb, 0x5f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xf6, 0xeb, 0xf8, 0x78, 0xf1, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotificationClient is the client API for Notification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotificationClient interface {
	Publish(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	MarkAll(ctx context.Context, in *MarkAllRequest, opts ...grpc.CallOption) (*MarkAllResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
}

type notificationClient struct {
	cc *grpc.ClientConn
}

func NewNotificationClient(cc *grpc.ClientConn) NotificationClient {
	return &notificationClient{cc}
}

func (c *notificationClient) Publish(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, "/notification.Notification/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, "/notification.Notification/Post", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/notification.Notification/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/notification.Notification/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) MarkAll(ctx context.Context, in *MarkAllRequest, opts ...grpc.CallOption) (*MarkAllResponse, error) {
	out := new(MarkAllResponse)
	err := c.cc.Invoke(ctx, "/notification.Notification/MarkAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/notification.Notification/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, "/notification.Notification/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServer is the server API for Notification service.
type NotificationServer interface {
	Publish(context.Context, *PostRequest) (*PostResponse, error)
	Post(context.Context, *PostRequest) (*PostResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	MarkAll(context.Context, *MarkAllRequest) (*MarkAllResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error)
}

// UnimplementedNotificationServer can be embedded to have forward compatible implementations.
type UnimplementedNotificationServer struct {
}

func (*UnimplementedNotificationServer) Publish(ctx context.Context, req *PostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (*UnimplementedNotificationServer) Post(ctx context.Context, req *PostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Post not implemented")
}
func (*UnimplementedNotificationServer) Query(ctx context.Context, req *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (*UnimplementedNotificationServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedNotificationServer) MarkAll(ctx context.Context, req *MarkAllRequest) (*MarkAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkAll not implemented")
}
func (*UnimplementedNotificationServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedNotificationServer) SendEmail(ctx context.Context, req *SendEmailRequest) (*SendEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}

func RegisterNotificationServer(s *grpc.Server, srv NotificationServer) {
	s.RegisterService(&_Notification_serviceDesc, srv)
}

func _Notification_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.Notification/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).Publish(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.Notification/Post",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).Post(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.Notification/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.Notification/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_MarkAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).MarkAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.Notification/MarkAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).MarkAll(ctx, req.(*MarkAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.Notification/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.Notification/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notification_serviceDesc = grpc.ServiceDesc{
	ServiceName: "notification.Notification",
	HandlerType: (*NotificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _Notification_Publish_Handler,
		},
		{
			MethodName: "Post",
			Handler:    _Notification_Post_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Notification_Query_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Notification_Update_Handler,
		},
		{
			MethodName: "MarkAll",
			Handler:    _Notification_MarkAll_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Notification_Delete_Handler,
		},
		{
			MethodName: "SendEmail",
			Handler:    _Notification_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification/notification.proto",
}
