// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: backup.proto

package backup

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BackupClient is the client API for Backup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackupClient interface {
	CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*CreateBackupResponse, error)
	ListBackup(ctx context.Context, in *ListBackupRequest, opts ...grpc.CallOption) (*ListBackupResponse, error)
	DetailBackup(ctx context.Context, in *DetailBackupRequest, opts ...grpc.CallOption) (*DetailBackupResponse, error)
	PreserveBackup(ctx context.Context, in *PreserveBackupRequest, opts ...grpc.CallOption) (*PreserveBackupResponse, error)
	RestoreBackup(ctx context.Context, in *RestoreBackupRequest, opts ...grpc.CallOption) (*RestoreBackupResponse, error)
	RestoreListBackup(ctx context.Context, in *RestoreListRequest, opts ...grpc.CallOption) (*RestoreListResponse, error)
	DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*DeleteBackupResponse, error)
	GetSettingBackup(ctx context.Context, in *GetSettingBackupRequest, opts ...grpc.CallOption) (*GetSettingBackupResponse, error)
	SaveSettingBackup(ctx context.Context, in *SaveSettingBackupRequest, opts ...grpc.CallOption) (*SaveSettingBackupResponse, error)
	AddLabelBackup(ctx context.Context, in *AddLabelRequest, opts ...grpc.CallOption) (*AddLabelResponse, error)
}

type backupClient struct {
	cc grpc.ClientConnInterface
}

func NewBackupClient(cc grpc.ClientConnInterface) BackupClient {
	return &backupClient{cc}
}

func (c *backupClient) CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*CreateBackupResponse, error) {
	out := new(CreateBackupResponse)
	err := c.cc.Invoke(ctx, "/backup.Backup/CreateBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupClient) ListBackup(ctx context.Context, in *ListBackupRequest, opts ...grpc.CallOption) (*ListBackupResponse, error) {
	out := new(ListBackupResponse)
	err := c.cc.Invoke(ctx, "/backup.Backup/ListBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupClient) DetailBackup(ctx context.Context, in *DetailBackupRequest, opts ...grpc.CallOption) (*DetailBackupResponse, error) {
	out := new(DetailBackupResponse)
	err := c.cc.Invoke(ctx, "/backup.Backup/DetailBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupClient) PreserveBackup(ctx context.Context, in *PreserveBackupRequest, opts ...grpc.CallOption) (*PreserveBackupResponse, error) {
	out := new(PreserveBackupResponse)
	err := c.cc.Invoke(ctx, "/backup.Backup/PreserveBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupClient) RestoreBackup(ctx context.Context, in *RestoreBackupRequest, opts ...grpc.CallOption) (*RestoreBackupResponse, error) {
	out := new(RestoreBackupResponse)
	err := c.cc.Invoke(ctx, "/backup.Backup/RestoreBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupClient) RestoreListBackup(ctx context.Context, in *RestoreListRequest, opts ...grpc.CallOption) (*RestoreListResponse, error) {
	out := new(RestoreListResponse)
	err := c.cc.Invoke(ctx, "/backup.Backup/RestoreListBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupClient) DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*DeleteBackupResponse, error) {
	out := new(DeleteBackupResponse)
	err := c.cc.Invoke(ctx, "/backup.Backup/DeleteBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupClient) GetSettingBackup(ctx context.Context, in *GetSettingBackupRequest, opts ...grpc.CallOption) (*GetSettingBackupResponse, error) {
	out := new(GetSettingBackupResponse)
	err := c.cc.Invoke(ctx, "/backup.Backup/GetSettingBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupClient) SaveSettingBackup(ctx context.Context, in *SaveSettingBackupRequest, opts ...grpc.CallOption) (*SaveSettingBackupResponse, error) {
	out := new(SaveSettingBackupResponse)
	err := c.cc.Invoke(ctx, "/backup.Backup/SaveSettingBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupClient) AddLabelBackup(ctx context.Context, in *AddLabelRequest, opts ...grpc.CallOption) (*AddLabelResponse, error) {
	out := new(AddLabelResponse)
	err := c.cc.Invoke(ctx, "/backup.Backup/AddLabelBackup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackupServer is the server API for Backup service.
// All implementations must embed UnimplementedBackupServer
// for forward compatibility
type BackupServer interface {
	CreateBackup(context.Context, *CreateBackupRequest) (*CreateBackupResponse, error)
	ListBackup(context.Context, *ListBackupRequest) (*ListBackupResponse, error)
	DetailBackup(context.Context, *DetailBackupRequest) (*DetailBackupResponse, error)
	PreserveBackup(context.Context, *PreserveBackupRequest) (*PreserveBackupResponse, error)
	RestoreBackup(context.Context, *RestoreBackupRequest) (*RestoreBackupResponse, error)
	RestoreListBackup(context.Context, *RestoreListRequest) (*RestoreListResponse, error)
	DeleteBackup(context.Context, *DeleteBackupRequest) (*DeleteBackupResponse, error)
	GetSettingBackup(context.Context, *GetSettingBackupRequest) (*GetSettingBackupResponse, error)
	SaveSettingBackup(context.Context, *SaveSettingBackupRequest) (*SaveSettingBackupResponse, error)
	AddLabelBackup(context.Context, *AddLabelRequest) (*AddLabelResponse, error)
	mustEmbedUnimplementedBackupServer()
}

// UnimplementedBackupServer must be embedded to have forward compatible implementations.
type UnimplementedBackupServer struct {
}

func (UnimplementedBackupServer) CreateBackup(context.Context, *CreateBackupRequest) (*CreateBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBackup not implemented")
}
func (UnimplementedBackupServer) ListBackup(context.Context, *ListBackupRequest) (*ListBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBackup not implemented")
}
func (UnimplementedBackupServer) DetailBackup(context.Context, *DetailBackupRequest) (*DetailBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetailBackup not implemented")
}
func (UnimplementedBackupServer) PreserveBackup(context.Context, *PreserveBackupRequest) (*PreserveBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreserveBackup not implemented")
}
func (UnimplementedBackupServer) RestoreBackup(context.Context, *RestoreBackupRequest) (*RestoreBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreBackup not implemented")
}
func (UnimplementedBackupServer) RestoreListBackup(context.Context, *RestoreListRequest) (*RestoreListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreListBackup not implemented")
}
func (UnimplementedBackupServer) DeleteBackup(context.Context, *DeleteBackupRequest) (*DeleteBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBackup not implemented")
}
func (UnimplementedBackupServer) GetSettingBackup(context.Context, *GetSettingBackupRequest) (*GetSettingBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSettingBackup not implemented")
}
func (UnimplementedBackupServer) SaveSettingBackup(context.Context, *SaveSettingBackupRequest) (*SaveSettingBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveSettingBackup not implemented")
}
func (UnimplementedBackupServer) AddLabelBackup(context.Context, *AddLabelRequest) (*AddLabelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLabelBackup not implemented")
}
func (UnimplementedBackupServer) mustEmbedUnimplementedBackupServer() {}

// UnsafeBackupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackupServer will
// result in compilation errors.
type UnsafeBackupServer interface {
	mustEmbedUnimplementedBackupServer()
}

func RegisterBackupServer(s grpc.ServiceRegistrar, srv BackupServer) {
	s.RegisterService(&Backup_ServiceDesc, srv)
}

func _Backup_CreateBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServer).CreateBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backup.Backup/CreateBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServer).CreateBackup(ctx, req.(*CreateBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backup_ListBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServer).ListBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backup.Backup/ListBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServer).ListBackup(ctx, req.(*ListBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backup_DetailBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServer).DetailBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backup.Backup/DetailBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServer).DetailBackup(ctx, req.(*DetailBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backup_PreserveBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreserveBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServer).PreserveBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backup.Backup/PreserveBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServer).PreserveBackup(ctx, req.(*PreserveBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backup_RestoreBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServer).RestoreBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backup.Backup/RestoreBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServer).RestoreBackup(ctx, req.(*RestoreBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backup_RestoreListBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServer).RestoreListBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backup.Backup/RestoreListBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServer).RestoreListBackup(ctx, req.(*RestoreListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backup_DeleteBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServer).DeleteBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backup.Backup/DeleteBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServer).DeleteBackup(ctx, req.(*DeleteBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backup_GetSettingBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServer).GetSettingBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backup.Backup/GetSettingBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServer).GetSettingBackup(ctx, req.(*GetSettingBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backup_SaveSettingBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveSettingBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServer).SaveSettingBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backup.Backup/SaveSettingBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServer).SaveSettingBackup(ctx, req.(*SaveSettingBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backup_AddLabelBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServer).AddLabelBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backup.Backup/AddLabelBackup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServer).AddLabelBackup(ctx, req.(*AddLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Backup_ServiceDesc is the grpc.ServiceDesc for Backup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Backup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backup.Backup",
	HandlerType: (*BackupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBackup",
			Handler:    _Backup_CreateBackup_Handler,
		},
		{
			MethodName: "ListBackup",
			Handler:    _Backup_ListBackup_Handler,
		},
		{
			MethodName: "DetailBackup",
			Handler:    _Backup_DetailBackup_Handler,
		},
		{
			MethodName: "PreserveBackup",
			Handler:    _Backup_PreserveBackup_Handler,
		},
		{
			MethodName: "RestoreBackup",
			Handler:    _Backup_RestoreBackup_Handler,
		},
		{
			MethodName: "RestoreListBackup",
			Handler:    _Backup_RestoreListBackup_Handler,
		},
		{
			MethodName: "DeleteBackup",
			Handler:    _Backup_DeleteBackup_Handler,
		},
		{
			MethodName: "GetSettingBackup",
			Handler:    _Backup_GetSettingBackup_Handler,
		},
		{
			MethodName: "SaveSettingBackup",
			Handler:    _Backup_SaveSettingBackup_Handler,
		},
		{
			MethodName: "AddLabelBackup",
			Handler:    _Backup_AddLabelBackup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backup.proto",
}
