// Code generated by MockGen. DO NOT EDIT.
// Source: api/models/Cluster.go

// Package mockdb is a generated GoMock package.
package mockdb

import (
	models "01cloud-api/api/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "github.com/jinzhu/gorm"
)

// MockClusterInterface is a mock of ClusterInterface interface.
type MockClusterInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClusterInterfaceMockRecorder
}

// MockClusterInterfaceMockRecorder is the mock recorder for MockClusterInterface.
type MockClusterInterfaceMockRecorder struct {
	mock *MockClusterInterface
}

// NewMockClusterInterface creates a new mock instance.
func NewMockClusterInterface(ctrl *gomock.Controller) *MockClusterInterface {
	mock := &MockClusterInterface{ctrl: ctrl}
	mock.recorder = &MockClusterInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterInterface) EXPECT() *MockClusterInterfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockClusterInterface) Delete(db *gorm.DB, id uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", db, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockClusterInterfaceMockRecorder) Delete(db, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClusterInterface)(nil).Delete), db, id)
}

// DeleteByClusterRequest mocks base method.
func (m *MockClusterInterface) DeleteByClusterRequest(db *gorm.DB, id uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByClusterRequest", db, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByClusterRequest indicates an expected call of DeleteByClusterRequest.
func (mr *MockClusterInterfaceMockRecorder) DeleteByClusterRequest(db, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByClusterRequest", reflect.TypeOf((*MockClusterInterface)(nil).DeleteByClusterRequest), db, id)
}

// Find mocks base method.
func (m *MockClusterInterface) Find(db *gorm.DB, pid uint64) (*models.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", db, pid)
	ret0, _ := ret[0].(*models.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockClusterInterfaceMockRecorder) Find(db, pid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockClusterInterface)(nil).Find), db, pid)
}

// FindAll mocks base method.
func (m *MockClusterInterface) FindAll(db *gorm.DB) (*[]models.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", db)
	ret0, _ := ret[0].(*[]models.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockClusterInterfaceMockRecorder) FindAll(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockClusterInterface)(nil).FindAll), db)
}

// FindAllClusterWithOrganizationId mocks base method.
func (m *MockClusterInterface) FindAllClusterWithOrganizationId(db *gorm.DB, oid uint64) (*[]models.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllClusterWithOrganizationId", db, oid)
	ret0, _ := ret[0].(*[]models.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllClusterWithOrganizationId indicates an expected call of FindAllClusterWithOrganizationId.
func (mr *MockClusterInterfaceMockRecorder) FindAllClusterWithOrganizationId(db, oid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllClusterWithOrganizationId", reflect.TypeOf((*MockClusterInterface)(nil).FindAllClusterWithOrganizationId), db, oid)
}

// FindAllClustersByRegion mocks base method.
func (m *MockClusterInterface) FindAllClustersByRegion(db *gorm.DB, org, region string) (*[]models.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllClustersByRegion", db, org, region)
	ret0, _ := ret[0].(*[]models.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllClustersByRegion indicates an expected call of FindAllClustersByRegion.
func (mr *MockClusterInterfaceMockRecorder) FindAllClustersByRegion(db, org, region interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllClustersByRegion", reflect.TypeOf((*MockClusterInterface)(nil).FindAllClustersByRegion), db, org, region)
}

// FindAllRegions mocks base method.
func (m *MockClusterInterface) FindAllRegions(db *gorm.DB, oid uint) (*[]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllRegions", db, oid)
	ret0, _ := ret[0].(*[]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllRegions indicates an expected call of FindAllRegions.
func (mr *MockClusterInterfaceMockRecorder) FindAllRegions(db, oid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllRegions", reflect.TypeOf((*MockClusterInterface)(nil).FindAllRegions), db, oid)
}

// FindAllWithInActive mocks base method.
func (m *MockClusterInterface) FindAllWithInActive(db *gorm.DB) (*[]models.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllWithInActive", db)
	ret0, _ := ret[0].(*[]models.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllWithInActive indicates an expected call of FindAllWithInActive.
func (mr *MockClusterInterfaceMockRecorder) FindAllWithInActive(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllWithInActive", reflect.TypeOf((*MockClusterInterface)(nil).FindAllWithInActive), db)
}

// FindByRegion mocks base method.
func (m *MockClusterInterface) FindByRegion(db *gorm.DB, region string, oid uint) (*models.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRegion", db, region, oid)
	ret0, _ := ret[0].(*models.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRegion indicates an expected call of FindByRegion.
func (mr *MockClusterInterfaceMockRecorder) FindByRegion(db, region, oid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRegion", reflect.TypeOf((*MockClusterInterface)(nil).FindByRegion), db, region, oid)
}

// FindByRegionWithDns mocks base method.
func (m *MockClusterInterface) FindByRegionWithDns(db *gorm.DB, region string, oid uint) (*models.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRegionWithDns", db, region, oid)
	ret0, _ := ret[0].(*models.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRegionWithDns indicates an expected call of FindByRegionWithDns.
func (mr *MockClusterInterfaceMockRecorder) FindByRegionWithDns(db, region, oid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRegionWithDns", reflect.TypeOf((*MockClusterInterface)(nil).FindByRegionWithDns), db, region, oid)
}

// FindRegions mocks base method.
func (m *MockClusterInterface) FindRegions(db *gorm.DB, oid uint) (*[]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRegions", db, oid)
	ret0, _ := ret[0].(*[]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRegions indicates an expected call of FindRegions.
func (mr *MockClusterInterfaceMockRecorder) FindRegions(db, oid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRegions", reflect.TypeOf((*MockClusterInterface)(nil).FindRegions), db, oid)
}

// FindWithDetails mocks base method.
func (m *MockClusterInterface) FindWithDetails(db *gorm.DB, pid uint64) (*models.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithDetails", db, pid)
	ret0, _ := ret[0].(*models.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWithDetails indicates an expected call of FindWithDetails.
func (mr *MockClusterInterfaceMockRecorder) FindWithDetails(db, pid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithDetails", reflect.TypeOf((*MockClusterInterface)(nil).FindWithDetails), db, pid)
}

// FindWithDns mocks base method.
func (m *MockClusterInterface) FindWithDns(db *gorm.DB, pid uint64) (*models.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithDns", db, pid)
	ret0, _ := ret[0].(*models.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWithDns indicates an expected call of FindWithDns.
func (mr *MockClusterInterfaceMockRecorder) FindWithDns(db, pid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithDns", reflect.TypeOf((*MockClusterInterface)(nil).FindWithDns), db, pid)
}

// FindZeroneCluster mocks base method.
func (m *MockClusterInterface) FindZeroneCluster(db *gorm.DB) (*models.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindZeroneCluster", db)
	ret0, _ := ret[0].(*models.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindZeroneCluster indicates an expected call of FindZeroneCluster.
func (mr *MockClusterInterfaceMockRecorder) FindZeroneCluster(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindZeroneCluster", reflect.TypeOf((*MockClusterInterface)(nil).FindZeroneCluster), db)
}

// Save mocks base method.
func (m *MockClusterInterface) Save(db *gorm.DB, data models.Cluster) (*models.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", db, data)
	ret0, _ := ret[0].(*models.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockClusterInterfaceMockRecorder) Save(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockClusterInterface)(nil).Save), db, data)
}

// Update mocks base method.
func (m *MockClusterInterface) Update(db *gorm.DB, data models.Cluster) (*models.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", db, data)
	ret0, _ := ret[0].(*models.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockClusterInterfaceMockRecorder) Update(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClusterInterface)(nil).Update), db, data)
}

// UpdateLabelsAndColor mocks base method.
func (m *MockClusterInterface) UpdateLabelsAndColor(db *gorm.DB, data models.Cluster) (*models.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLabelsAndColor", db, data)
	ret0, _ := ret[0].(*models.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLabelsAndColor indicates an expected call of UpdateLabelsAndColor.
func (mr *MockClusterInterfaceMockRecorder) UpdateLabelsAndColor(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLabelsAndColor", reflect.TypeOf((*MockClusterInterface)(nil).UpdateLabelsAndColor), db, data)
}
