// Code generated by MockGen. DO NOT EDIT.
// Source: api/models/DNS_Interface.go

// Package mockdb is a generated GoMock package.
package mockdb

import (
	models "01cloud-api/api/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "github.com/jinzhu/gorm"
)

// MockIDNS is a mock of IDNS interface.
type MockIDNS struct {
	ctrl     *gomock.Controller
	recorder *MockIDNSMockRecorder
}

// MockIDNSMockRecorder is the mock recorder for MockIDNS.
type MockIDNSMockRecorder struct {
	mock *MockIDNS
}

// NewMockIDNS creates a new mock instance.
func NewMockIDNS(ctrl *gomock.Controller) *MockIDNS {
	mock := &MockIDNS{ctrl: ctrl}
	mock.recorder = &MockIDNSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDNS) EXPECT() *MockIDNSMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockIDNS) Delete(db *gorm.DB, id uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", db, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIDNSMockRecorder) Delete(db, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIDNS)(nil).Delete), db, id)
}

// Find mocks base method.
func (m *MockIDNS) Find(db *gorm.DB, pid uint64) (*models.DNS, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", db, pid)
	ret0, _ := ret[0].(*models.DNS)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIDNSMockRecorder) Find(db, pid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIDNS)(nil).Find), db, pid)
}

// FindAll mocks base method.
func (m *MockIDNS) FindAll(db *gorm.DB) (*[]models.DNS, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", db)
	ret0, _ := ret[0].(*[]models.DNS)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockIDNSMockRecorder) FindAll(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockIDNS)(nil).FindAll), db)
}

// FindAllByOrganization mocks base method.
func (m *MockIDNS) FindAllByOrganization(db *gorm.DB, orgId uint) (*[]models.DNS, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByOrganization", db, orgId)
	ret0, _ := ret[0].(*[]models.DNS)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByOrganization indicates an expected call of FindAllByOrganization.
func (mr *MockIDNSMockRecorder) FindAllByOrganization(db, orgId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByOrganization", reflect.TypeOf((*MockIDNS)(nil).FindAllByOrganization), db, orgId)
}

// FindAllWithInactive mocks base method.
func (m *MockIDNS) FindAllWithInactive(db *gorm.DB) (*[]models.DNS, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllWithInactive", db)
	ret0, _ := ret[0].(*[]models.DNS)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllWithInactive indicates an expected call of FindAllWithInactive.
func (mr *MockIDNSMockRecorder) FindAllWithInactive(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllWithInactive", reflect.TypeOf((*MockIDNS)(nil).FindAllWithInactive), db)
}

// IsNameExists mocks base method.
func (m *MockIDNS) IsNameExists(db *gorm.DB, oid uint64, name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNameExists", db, oid, name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNameExists indicates an expected call of IsNameExists.
func (mr *MockIDNSMockRecorder) IsNameExists(db, oid, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNameExists", reflect.TypeOf((*MockIDNS)(nil).IsNameExists), db, oid, name)
}

// Save mocks base method.
func (m *MockIDNS) Save(db *gorm.DB, data *models.DNS) (*models.DNS, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", db, data)
	ret0, _ := ret[0].(*models.DNS)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIDNSMockRecorder) Save(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIDNS)(nil).Save), db, data)
}

// Update mocks base method.
func (m *MockIDNS) Update(db *gorm.DB, data *models.DNS) (*models.DNS, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", db, data)
	ret0, _ := ret[0].(*models.DNS)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIDNSMockRecorder) Update(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIDNS)(nil).Update), db, data)
}
