// Code generated by MockGen. DO NOT EDIT.
// Source: api/models/Groups.go

// Package mockdb is a generated GoMock package.
package mockdb

import (
	models "01cloud-api/api/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "github.com/jinzhu/gorm"
)

// MockGroupInterface is a mock of GroupInterface interface.
type MockGroupInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGroupInterfaceMockRecorder
}

// MockGroupInterfaceMockRecorder is the mock recorder for MockGroupInterface.
type MockGroupInterfaceMockRecorder struct {
	mock *MockGroupInterface
}

// NewMockGroupInterface creates a new mock instance.
func NewMockGroupInterface(ctrl *gomock.Controller) *MockGroupInterface {
	mock := &MockGroupInterface{ctrl: ctrl}
	mock.recorder = &MockGroupInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupInterface) EXPECT() *MockGroupInterfaceMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockGroupInterface) AddMember(db *gorm.DB, user *models.User, data *models.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", db, user, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockGroupInterfaceMockRecorder) AddMember(db, user, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockGroupInterface)(nil).AddMember), db, user, data)
}

// Delete mocks base method.
func (m *MockGroupInterface) Delete(db *gorm.DB, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", db, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockGroupInterfaceMockRecorder) Delete(db, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGroupInterface)(nil).Delete), db, id)
}

// DeleteMember mocks base method.
func (m *MockGroupInterface) DeleteMember(db *gorm.DB, user *models.User, data *models.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMember", db, user, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMember indicates an expected call of DeleteMember.
func (mr *MockGroupInterfaceMockRecorder) DeleteMember(db, user, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMember", reflect.TypeOf((*MockGroupInterface)(nil).DeleteMember), db, user, data)
}

// Find mocks base method.
func (m *MockGroupInterface) Find(db *gorm.DB, gid uint64, oid uint) (*models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", db, gid, oid)
	ret0, _ := ret[0].(*models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockGroupInterfaceMockRecorder) Find(db, gid, oid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockGroupInterface)(nil).Find), db, gid, oid)
}

// FindAll mocks base method.
func (m *MockGroupInterface) FindAll(db *gorm.DB, userID uint64, query string) (*[]models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", db, userID, query)
	ret0, _ := ret[0].(*[]models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockGroupInterfaceMockRecorder) FindAll(db, userID, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockGroupInterface)(nil).FindAll), db, userID, query)
}

// Save mocks base method.
func (m *MockGroupInterface) Save(db *gorm.DB, data *models.Group) (*models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", db, data)
	ret0, _ := ret[0].(*models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockGroupInterfaceMockRecorder) Save(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockGroupInterface)(nil).Save), db, data)
}

// Update mocks base method.
func (m *MockGroupInterface) Update(db *gorm.DB, data *models.Group) (*models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", db, data)
	ret0, _ := ret[0].(*models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockGroupInterfaceMockRecorder) Update(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGroupInterface)(nil).Update), db, data)
}
