// Code generated by MockGen. DO NOT EDIT.
// Source: api/models/Loadbalancer_interface.go

// Package mockdb is a generated GoMock package.
package mockdb

import (
	models "01cloud-api/api/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "github.com/jinzhu/gorm"
)

// MockLoadBalancerInterface is a mock of LoadBalancerInterface interface.
type MockLoadBalancerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLoadBalancerInterfaceMockRecorder
}

// MockLoadBalancerInterfaceMockRecorder is the mock recorder for MockLoadBalancerInterface.
type MockLoadBalancerInterfaceMockRecorder struct {
	mock *MockLoadBalancerInterface
}

// NewMockLoadBalancerInterface creates a new mock instance.
func NewMockLoadBalancerInterface(ctrl *gomock.Controller) *MockLoadBalancerInterface {
	mock := &MockLoadBalancerInterface{ctrl: ctrl}
	mock.recorder = &MockLoadBalancerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoadBalancerInterface) EXPECT() *MockLoadBalancerInterfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockLoadBalancerInterface) Delete(db *gorm.DB, uid uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", db, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockLoadBalancerInterfaceMockRecorder) Delete(db, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLoadBalancerInterface)(nil).Delete), db, uid)
}

// Find mocks base method.
func (m *MockLoadBalancerInterface) Find(db *gorm.DB, pid uint64) (*models.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", db, pid)
	ret0, _ := ret[0].(*models.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockLoadBalancerInterfaceMockRecorder) Find(db, pid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockLoadBalancerInterface)(nil).Find), db, pid)
}

// FindAllByProject mocks base method.
func (m *MockLoadBalancerInterface) FindAllByProject(db *gorm.DB, pid uint64) (*[]models.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByProject", db, pid)
	ret0, _ := ret[0].(*[]models.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByProject indicates an expected call of FindAllByProject.
func (mr *MockLoadBalancerInterfaceMockRecorder) FindAllByProject(db, pid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByProject", reflect.TypeOf((*MockLoadBalancerInterface)(nil).FindAllByProject), db, pid)
}

// Save mocks base method.
func (m *MockLoadBalancerInterface) Save(db *gorm.DB, data *models.LoadBalancer) (*models.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", db, data)
	ret0, _ := ret[0].(*models.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockLoadBalancerInterfaceMockRecorder) Save(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLoadBalancerInterface)(nil).Save), db, data)
}

// Update mocks base method.
func (m *MockLoadBalancerInterface) Update(db *gorm.DB, data *models.LoadBalancer) (*models.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", db, data)
	ret0, _ := ret[0].(*models.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockLoadBalancerInterfaceMockRecorder) Update(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLoadBalancerInterface)(nil).Update), db, data)
}
