// Code generated by MockGen. DO NOT EDIT.
// Source: api/models/Activities_interface.go

// Package mockdb is a generated GoMock package.
package mockdb

import (
	models "01cloud-api/api/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "github.com/jinzhu/gorm"
)

// MockActivityInterface is a mock of ActivityInterface interface.
type MockActivityInterface struct {
	ctrl     *gomock.Controller
	recorder *MockActivityInterfaceMockRecorder
}

// MockActivityInterfaceMockRecorder is the mock recorder for MockActivityInterface.
type MockActivityInterfaceMockRecorder struct {
	mock *MockActivityInterface
}

// NewMockActivityInterface creates a new mock instance.
func NewMockActivityInterface(ctrl *gomock.Controller) *MockActivityInterface {
	mock := &MockActivityInterface{ctrl: ctrl}
	mock.recorder = &MockActivityInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityInterface) EXPECT() *MockActivityInterfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockActivityInterface) Delete(db *gorm.DB, uid uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", db, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockActivityInterfaceMockRecorder) Delete(db, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockActivityInterface)(nil).Delete), db, uid)
}

// Find mocks base method.
func (m *MockActivityInterface) Find(db *gorm.DB, pid uint64) (*models.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", db, pid)
	ret0, _ := ret[0].(*models.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockActivityInterfaceMockRecorder) Find(db, pid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockActivityInterface)(nil).Find), db, pid)
}

// FindAll mocks base method.
func (m *MockActivityInterface) FindAll(db *gorm.DB) (*[]models.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", db)
	ret0, _ := ret[0].(*[]models.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockActivityInterfaceMockRecorder) FindAll(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockActivityInterface)(nil).FindAll), db)
}

// FindAllActivityByOrganization mocks base method.
func (m *MockActivityInterface) FindAllActivityByOrganization(db *gorm.DB, oid uint, limit, offset int, action, module, startdate, enddate string, userid int) (*[]models.Activity, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllActivityByOrganization", db, oid, limit, offset, action, module, startdate, enddate, userid)
	ret0, _ := ret[0].(*[]models.Activity)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAllActivityByOrganization indicates an expected call of FindAllActivityByOrganization.
func (mr *MockActivityInterfaceMockRecorder) FindAllActivityByOrganization(db, oid, limit, offset, action, module, startdate, enddate, userid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllActivityByOrganization", reflect.TypeOf((*MockActivityInterface)(nil).FindAllActivityByOrganization), db, oid, limit, offset, action, module, startdate, enddate, userid)
}

// FindAllActivityByProject mocks base method.
func (m *MockActivityInterface) FindAllActivityByProject(db *gorm.DB, pid uint, limit, offset int, action, module, startdate, enddate string, userid int) (*[]models.Activity, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllActivityByProject", db, pid, limit, offset, action, module, startdate, enddate, userid)
	ret0, _ := ret[0].(*[]models.Activity)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAllActivityByProject indicates an expected call of FindAllActivityByProject.
func (mr *MockActivityInterfaceMockRecorder) FindAllActivityByProject(db, pid, limit, offset, action, module, startdate, enddate, userid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllActivityByProject", reflect.TypeOf((*MockActivityInterface)(nil).FindAllActivityByProject), db, pid, limit, offset, action, module, startdate, enddate, userid)
}

// Save mocks base method.
func (m *MockActivityInterface) Save(db *gorm.DB, data models.Activity) (*models.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", db, data)
	ret0, _ := ret[0].(*models.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockActivityInterfaceMockRecorder) Save(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockActivityInterface)(nil).Save), db, data)
}

// Update mocks base method.
func (m *MockActivityInterface) Update(db *gorm.DB, data models.Activity) (*models.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", db, data)
	ret0, _ := ret[0].(*models.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockActivityInterfaceMockRecorder) Update(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockActivityInterface)(nil).Update), db, data)
}
