// Code generated by MockGen. DO NOT EDIT.
// Source: api/models/OrganizationPlan.go

// Package mockdb is a generated GoMock package.
package mockdb

import (
	models "01cloud-api/api/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "github.com/jinzhu/gorm"
)

// MockOrganizationPlanInterface is a mock of OrganizationPlanInterface interface.
type MockOrganizationPlanInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationPlanInterfaceMockRecorder
}

// MockOrganizationPlanInterfaceMockRecorder is the mock recorder for MockOrganizationPlanInterface.
type MockOrganizationPlanInterfaceMockRecorder struct {
	mock *MockOrganizationPlanInterface
}

// NewMockOrganizationPlanInterface creates a new mock instance.
func NewMockOrganizationPlanInterface(ctrl *gomock.Controller) *MockOrganizationPlanInterface {
	mock := &MockOrganizationPlanInterface{ctrl: ctrl}
	mock.recorder = &MockOrganizationPlanInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationPlanInterface) EXPECT() *MockOrganizationPlanInterfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockOrganizationPlanInterface) Delete(db *gorm.DB, id uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", db, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockOrganizationPlanInterfaceMockRecorder) Delete(db, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrganizationPlanInterface)(nil).Delete), db, id)
}

// Find mocks base method.
func (m *MockOrganizationPlanInterface) Find(db *gorm.DB, pid uint64) (*models.OrganizationPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", db, pid)
	ret0, _ := ret[0].(*models.OrganizationPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockOrganizationPlanInterfaceMockRecorder) Find(db, pid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockOrganizationPlanInterface)(nil).Find), db, pid)
}

// FindAll mocks base method.
func (m *MockOrganizationPlanInterface) FindAll(db *gorm.DB) (*[]models.OrganizationPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", db)
	ret0, _ := ret[0].(*[]models.OrganizationPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockOrganizationPlanInterfaceMockRecorder) FindAll(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockOrganizationPlanInterface)(nil).FindAll), db)
}

// FindAllWithInActive mocks base method.
func (m *MockOrganizationPlanInterface) FindAllWithInActive(db *gorm.DB) (*[]models.OrganizationPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllWithInActive", db)
	ret0, _ := ret[0].(*[]models.OrganizationPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllWithInActive indicates an expected call of FindAllWithInActive.
func (mr *MockOrganizationPlanInterfaceMockRecorder) FindAllWithInActive(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllWithInActive", reflect.TypeOf((*MockOrganizationPlanInterface)(nil).FindAllWithInActive), db)
}

// Save mocks base method.
func (m *MockOrganizationPlanInterface) Save(db *gorm.DB, data *models.OrganizationPlan) (*models.OrganizationPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", db, data)
	ret0, _ := ret[0].(*models.OrganizationPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockOrganizationPlanInterfaceMockRecorder) Save(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockOrganizationPlanInterface)(nil).Save), db, data)
}

// Update mocks base method.
func (m *MockOrganizationPlanInterface) Update(db *gorm.DB, data *models.OrganizationPlan) (*models.OrganizationPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", db, data)
	ret0, _ := ret[0].(*models.OrganizationPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockOrganizationPlanInterfaceMockRecorder) Update(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrganizationPlanInterface)(nil).Update), db, data)
}
