// Code generated by MockGen. DO NOT EDIT.
// Source: api/models/Organization_Interface.go

// Package mockdb is a generated GoMock package.
package mockdb

import (
	models "01cloud-api/api/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "github.com/jinzhu/gorm"
)

// MockOrganizationInterface is a mock of OrganizationInterface interface.
type MockOrganizationInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationInterfaceMockRecorder
}

// MockOrganizationInterfaceMockRecorder is the mock recorder for MockOrganizationInterface.
type MockOrganizationInterfaceMockRecorder struct {
	mock *MockOrganizationInterface
}

// NewMockOrganizationInterface creates a new mock instance.
func NewMockOrganizationInterface(ctrl *gomock.Controller) *MockOrganizationInterface {
	mock := &MockOrganizationInterface{ctrl: ctrl}
	mock.recorder = &MockOrganizationInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationInterface) EXPECT() *MockOrganizationInterfaceMockRecorder {
	return m.recorder
}

// ActiveDeactiveOrganization mocks base method.
func (m *MockOrganizationInterface) ActiveDeactiveOrganization(db *gorm.DB, oid uint, active bool) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveDeactiveOrganization", db, oid, active)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActiveDeactiveOrganization indicates an expected call of ActiveDeactiveOrganization.
func (mr *MockOrganizationInterfaceMockRecorder) ActiveDeactiveOrganization(db, oid, active interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveDeactiveOrganization", reflect.TypeOf((*MockOrganizationInterface)(nil).ActiveDeactiveOrganization), db, oid, active)
}

// CountOrginationByUser mocks base method.
func (m *MockOrganizationInterface) CountOrginationByUser(db *gorm.DB, uid uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOrginationByUser", db, uid)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOrginationByUser indicates an expected call of CountOrginationByUser.
func (mr *MockOrganizationInterfaceMockRecorder) CountOrginationByUser(db, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOrginationByUser", reflect.TypeOf((*MockOrganizationInterface)(nil).CountOrginationByUser), db, uid)
}

// Delete mocks base method.
func (m *MockOrganizationInterface) Delete(db *gorm.DB, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", db, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockOrganizationInterfaceMockRecorder) Delete(db, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrganizationInterface)(nil).Delete), db, id)
}

// Find mocks base method.
func (m *MockOrganizationInterface) Find(db *gorm.DB, oid uint) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", db, oid)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockOrganizationInterfaceMockRecorder) Find(db, oid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockOrganizationInterface)(nil).Find), db, oid)
}

// FindAll mocks base method.
func (m *MockOrganizationInterface) FindAll(db *gorm.DB, userID uint, active bool, query string) (*[]models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", db, userID, active, query)
	ret0, _ := ret[0].(*[]models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockOrganizationInterfaceMockRecorder) FindAll(db, userID, active, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockOrganizationInterface)(nil).FindAll), db, userID, active, query)
}

// Save mocks base method.
func (m *MockOrganizationInterface) Save(db *gorm.DB, data *models.Organization) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", db, data)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockOrganizationInterfaceMockRecorder) Save(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockOrganizationInterface)(nil).Save), db, data)
}

// Update mocks base method.
func (m *MockOrganizationInterface) Update(db *gorm.DB, data *models.Organization) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", db, data)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockOrganizationInterfaceMockRecorder) Update(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrganizationInterface)(nil).Update), db, data)
}
