// Code generated by MockGen. DO NOT EDIT.
// Source: api/models/Project.go

// Package mockdb is a generated GoMock package.
package mockdb

import (
	models "01cloud-api/api/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "github.com/jinzhu/gorm"
)

// MockIProject is a mock of IProject interface.
type MockIProject struct {
	ctrl     *gomock.Controller
	recorder *MockIProjectMockRecorder
}

// MockIProjectMockRecorder is the mock recorder for MockIProject.
type MockIProjectMockRecorder struct {
	mock *MockIProject
}

// NewMockIProject creates a new mock instance.
func NewMockIProject(ctrl *gomock.Controller) *MockIProject {
	mock := &MockIProject{ctrl: ctrl}
	mock.recorder = &MockIProjectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProject) EXPECT() *MockIProjectMockRecorder {
	return m.recorder
}

// ActiveDeactiveAll mocks base method.
func (m *MockIProject) ActiveDeactiveAll(db *gorm.DB, data *models.Project, userId uint64, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveDeactiveAll", db, data, userId, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActiveDeactiveAll indicates an expected call of ActiveDeactiveAll.
func (mr *MockIProjectMockRecorder) ActiveDeactiveAll(db, data, userId, isActive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveDeactiveAll", reflect.TypeOf((*MockIProject)(nil).ActiveDeactiveAll), db, data, userId, isActive)
}

// ChangeIsActive mocks base method.
func (m *MockIProject) ChangeIsActive(db *gorm.DB, data *models.Project, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeIsActive", db, data, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeIsActive indicates an expected call of ChangeIsActive.
func (mr *MockIProjectMockRecorder) ChangeIsActive(db, data, isActive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeIsActive", reflect.TypeOf((*MockIProject)(nil).ChangeIsActive), db, data, isActive)
}

// Delete mocks base method.
func (m *MockIProject) Delete(db *gorm.DB, id uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", db, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIProjectMockRecorder) Delete(db, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIProject)(nil).Delete), db, id)
}

// DeleteProjectOwner mocks base method.
func (m *MockIProject) DeleteProjectOwner(db *gorm.DB, userID, oid uint64) (*models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProjectOwner", db, userID, oid)
	ret0, _ := ret[0].(*models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProjectOwner indicates an expected call of DeleteProjectOwner.
func (mr *MockIProjectMockRecorder) DeleteProjectOwner(db, userID, oid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProjectOwner", reflect.TypeOf((*MockIProject)(nil).DeleteProjectOwner), db, userID, oid)
}

// Find mocks base method.
func (m *MockIProject) Find(db *gorm.DB, pid uint64) (*models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", db, pid)
	ret0, _ := ret[0].(*models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIProjectMockRecorder) Find(db, pid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIProject)(nil).Find), db, pid)
}

// FindAll mocks base method.
func (m *MockIProject) FindAll(db *gorm.DB, data *models.Project) (*[]models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", db, data)
	ret0, _ := ret[0].(*[]models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockIProjectMockRecorder) FindAll(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockIProject)(nil).FindAll), db, data)
}

// FindAllByUser mocks base method.
func (m *MockIProject) FindAllByUser(db *gorm.DB, userID uint, data *models.Project) ([]models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByUser", db, userID, data)
	ret0, _ := ret[0].([]models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByUser indicates an expected call of FindAllByUser.
func (mr *MockIProjectMockRecorder) FindAllByUser(db, userID, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByUser", reflect.TypeOf((*MockIProject)(nil).FindAllByUser), db, userID, data)
}

// FindAllDeactivatedProjectsByThresholdDays mocks base method.
func (m *MockIProject) FindAllDeactivatedProjectsByThresholdDays(db *gorm.DB, thresholdDays int) (*[]models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllDeactivatedProjectsByThresholdDays", db, thresholdDays)
	ret0, _ := ret[0].(*[]models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllDeactivatedProjectsByThresholdDays indicates an expected call of FindAllDeactivatedProjectsByThresholdDays.
func (mr *MockIProjectMockRecorder) FindAllDeactivatedProjectsByThresholdDays(db, thresholdDays interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllDeactivatedProjectsByThresholdDays", reflect.TypeOf((*MockIProject)(nil).FindAllDeactivatedProjectsByThresholdDays), db, thresholdDays)
}

// FindAllDeactivatedProjectsByThresholdDaysByUser mocks base method.
func (m *MockIProject) FindAllDeactivatedProjectsByThresholdDaysByUser(db *gorm.DB, userId uint, thresholdDays int) (*[]models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllDeactivatedProjectsByThresholdDaysByUser", db, userId, thresholdDays)
	ret0, _ := ret[0].(*[]models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllDeactivatedProjectsByThresholdDaysByUser indicates an expected call of FindAllDeactivatedProjectsByThresholdDaysByUser.
func (mr *MockIProjectMockRecorder) FindAllDeactivatedProjectsByThresholdDaysByUser(db, userId, thresholdDays interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllDeactivatedProjectsByThresholdDaysByUser", reflect.TypeOf((*MockIProject)(nil).FindAllDeactivatedProjectsByThresholdDaysByUser), db, userId, thresholdDays)
}

// FindAllProjects mocks base method.
func (m *MockIProject) FindAllProjects(db *gorm.DB) (*[]models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllProjects", db)
	ret0, _ := ret[0].(*[]models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllProjects indicates an expected call of FindAllProjects.
func (mr *MockIProjectMockRecorder) FindAllProjects(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllProjects", reflect.TypeOf((*MockIProject)(nil).FindAllProjects), db)
}

// FindProject mocks base method.
func (m *MockIProject) FindProject(db *gorm.DB, oid uint) (*[]models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProject", db, oid)
	ret0, _ := ret[0].(*[]models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProject indicates an expected call of FindProject.
func (mr *MockIProjectMockRecorder) FindProject(db, oid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProject", reflect.TypeOf((*MockIProject)(nil).FindProject), db, oid)
}

// FindUserProjectOnly mocks base method.
func (m *MockIProject) FindUserProjectOnly(db *gorm.DB, userID, oid uint) ([]models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserProjectOnly", db, userID, oid)
	ret0, _ := ret[0].([]models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserProjectOnly indicates an expected call of FindUserProjectOnly.
func (mr *MockIProjectMockRecorder) FindUserProjectOnly(db, userID, oid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserProjectOnly", reflect.TypeOf((*MockIProject)(nil).FindUserProjectOnly), db, userID, oid)
}

// GetProjectByName mocks base method.
func (m *MockIProject) GetProjectByName(db *gorm.DB, name string, org_id uint64) (models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectByName", db, name, org_id)
	ret0, _ := ret[0].(models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectByName indicates an expected call of GetProjectByName.
func (mr *MockIProjectMockRecorder) GetProjectByName(db, name, org_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectByName", reflect.TypeOf((*MockIProject)(nil).GetProjectByName), db, name, org_id)
}

// IsNameExists mocks base method.
func (m *MockIProject) IsNameExists(db *gorm.DB, userID uint, name string, data *models.Project) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNameExists", db, userID, name, data)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNameExists indicates an expected call of IsNameExists.
func (mr *MockIProjectMockRecorder) IsNameExists(db, userID, name, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNameExists", reflect.TypeOf((*MockIProject)(nil).IsNameExists), db, userID, name, data)
}

// Rename mocks base method.
func (m *MockIProject) Rename(db *gorm.DB, name string, proj *models.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", db, name, proj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockIProjectMockRecorder) Rename(db, name, proj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockIProject)(nil).Rename), db, name, proj)
}

// Save mocks base method.
func (m *MockIProject) Save(db *gorm.DB, data *models.Project) (*models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", db, data)
	ret0, _ := ret[0].(*models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIProjectMockRecorder) Save(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIProject)(nil).Save), db, data)
}

// SearchProject mocks base method.
func (m *MockIProject) SearchProject(db *gorm.DB, userID uint, query string) ([]models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchProject", db, userID, query)
	ret0, _ := ret[0].([]models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchProject indicates an expected call of SearchProject.
func (mr *MockIProjectMockRecorder) SearchProject(db, userID, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchProject", reflect.TypeOf((*MockIProject)(nil).SearchProject), db, userID, query)
}

// Update mocks base method.
func (m *MockIProject) Update(db *gorm.DB, data *models.Project) (*models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", db, data)
	ret0, _ := ret[0].(*models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIProjectMockRecorder) Update(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIProject)(nil).Update), db, data)
}

// UpdateUsageQuota mocks base method.
func (m *MockIProject) UpdateUsageQuota(db *gorm.DB, data *models.Project) (*models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUsageQuota", db, data)
	ret0, _ := ret[0].(*models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUsageQuota indicates an expected call of UpdateUsageQuota.
func (mr *MockIProjectMockRecorder) UpdateUsageQuota(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUsageQuota", reflect.TypeOf((*MockIProject)(nil).UpdateUsageQuota), db, data)
}
