// Code generated by MockGen. DO NOT EDIT.
// Source: api/models/Resource_interface.go

// Package mockdb is a generated GoMock package.
package mockdb

import (
	models "01cloud-api/api/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "github.com/jinzhu/gorm"
)

// MockResourceInterface is a mock of ResourceInterface interface.
type MockResourceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockResourceInterfaceMockRecorder
}

// MockResourceInterfaceMockRecorder is the mock recorder for MockResourceInterface.
type MockResourceInterfaceMockRecorder struct {
	mock *MockResourceInterface
}

// NewMockResourceInterface creates a new mock instance.
func NewMockResourceInterface(ctrl *gomock.Controller) *MockResourceInterface {
	mock := &MockResourceInterface{ctrl: ctrl}
	mock.recorder = &MockResourceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceInterface) EXPECT() *MockResourceInterfaceMockRecorder {
	return m.recorder
}

// CheckResourceLimit mocks base method.
func (m *MockResourceInterface) CheckResourceLimit(db *gorm.DB, org *models.Organization, data *models.Resource) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckResourceLimit", db, org, data)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckResourceLimit indicates an expected call of CheckResourceLimit.
func (mr *MockResourceInterfaceMockRecorder) CheckResourceLimit(db, org, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckResourceLimit", reflect.TypeOf((*MockResourceInterface)(nil).CheckResourceLimit), db, org, data)
}

// Delete mocks base method.
func (m *MockResourceInterface) Delete(db *gorm.DB, uid uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", db, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockResourceInterfaceMockRecorder) Delete(db, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockResourceInterface)(nil).Delete), db, uid)
}

// Find mocks base method.
func (m *MockResourceInterface) Find(db *gorm.DB, pid uint64) (*models.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", db, pid)
	ret0, _ := ret[0].(*models.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockResourceInterfaceMockRecorder) Find(db, pid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockResourceInterface)(nil).Find), db, pid)
}

// FindAll mocks base method.
func (m *MockResourceInterface) FindAll(db *gorm.DB, data *models.Resource) (*[]models.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", db, data)
	ret0, _ := ret[0].(*[]models.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockResourceInterfaceMockRecorder) FindAll(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockResourceInterface)(nil).FindAll), db, data)
}

// FindAllWithInactive mocks base method.
func (m *MockResourceInterface) FindAllWithInactive(db *gorm.DB, data *models.Resource) (*[]models.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllWithInactive", db, data)
	ret0, _ := ret[0].(*[]models.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllWithInactive indicates an expected call of FindAllWithInactive.
func (mr *MockResourceInterfaceMockRecorder) FindAllWithInactive(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllWithInactive", reflect.TypeOf((*MockResourceInterface)(nil).FindAllWithInactive), db, data)
}

// IsNameExists mocks base method.
func (m *MockResourceInterface) IsNameExists(db *gorm.DB, oId uint, name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNameExists", db, oId, name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNameExists indicates an expected call of IsNameExists.
func (mr *MockResourceInterfaceMockRecorder) IsNameExists(db, oId, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNameExists", reflect.TypeOf((*MockResourceInterface)(nil).IsNameExists), db, oId, name)
}

// Save mocks base method.
func (m *MockResourceInterface) Save(db *gorm.DB, data *models.Resource) (*models.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", db, data)
	ret0, _ := ret[0].(*models.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockResourceInterfaceMockRecorder) Save(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockResourceInterface)(nil).Save), db, data)
}

// Update mocks base method.
func (m *MockResourceInterface) Update(db *gorm.DB, data *models.Resource) (*models.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", db, data)
	ret0, _ := ret[0].(*models.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockResourceInterfaceMockRecorder) Update(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockResourceInterface)(nil).Update), db, data)
}
