// Code generated by MockGen. DO NOT EDIT.
// Source: api/models/Session.go

// Package mockdb is a generated GoMock package.
package mockdb

import (
	models "01cloud-api/api/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "github.com/jinzhu/gorm"
)

// MockSessionInterface is a mock of SessionInterface interface.
type MockSessionInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSessionInterfaceMockRecorder
}

// MockSessionInterfaceMockRecorder is the mock recorder for MockSessionInterface.
type MockSessionInterfaceMockRecorder struct {
	mock *MockSessionInterface
}

// NewMockSessionInterface creates a new mock instance.
func NewMockSessionInterface(ctrl *gomock.Controller) *MockSessionInterface {
	mock := &MockSessionInterface{ctrl: ctrl}
	mock.recorder = &MockSessionInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionInterface) EXPECT() *MockSessionInterfaceMockRecorder {
	return m.recorder
}

// GetAllSessionByUserId mocks base method.
func (m *MockSessionInterface) GetAllSessionByUserId(db *gorm.DB, userid uint, limit, offset int) (*[]models.Session, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSessionByUserId", db, userid, limit, offset)
	ret0, _ := ret[0].(*[]models.Session)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllSessionByUserId indicates an expected call of GetAllSessionByUserId.
func (mr *MockSessionInterfaceMockRecorder) GetAllSessionByUserId(db, userid, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSessionByUserId", reflect.TypeOf((*MockSessionInterface)(nil).GetAllSessionByUserId), db, userid, limit, offset)
}

// GetLastSessionId mocks base method.
func (m *MockSessionInterface) GetLastSessionId(db *gorm.DB, userid uint) uint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastSessionId", db, userid)
	ret0, _ := ret[0].(uint)
	return ret0
}

// GetLastSessionId indicates an expected call of GetLastSessionId.
func (mr *MockSessionInterfaceMockRecorder) GetLastSessionId(db, userid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastSessionId", reflect.TypeOf((*MockSessionInterface)(nil).GetLastSessionId), db, userid)
}

// SaveSession mocks base method.
func (m *MockSessionInterface) SaveSession(db *gorm.DB, data *models.Session) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSession", db, data)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveSession indicates an expected call of SaveSession.
func (mr *MockSessionInterfaceMockRecorder) SaveSession(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSession", reflect.TypeOf((*MockSessionInterface)(nil).SaveSession), db, data)
}
