// Code generated by MockGen. DO NOT EDIT.
// Source: api/models/Storage_interface.go

// Package mockdb is a generated GoMock package.
package mockdb

import (
	models "01cloud-api/api/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStorageInterface is a mock of StorageInterface interface.
type MockStorageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStorageInterfaceMockRecorder
}

// MockStorageInterfaceMockRecorder is the mock recorder for MockStorageInterface.
type MockStorageInterfaceMockRecorder struct {
	mock *MockStorageInterface
}

// NewMockStorageInterface creates a new mock instance.
func NewMockStorageInterface(ctrl *gomock.Controller) *MockStorageInterface {
	mock := &MockStorageInterface{ctrl: ctrl}
	mock.recorder = &MockStorageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageInterface) EXPECT() *MockStorageInterfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockStorageInterface) Delete(uid uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockStorageInterfaceMockRecorder) Delete(uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStorageInterface)(nil).Delete), uid)
}

// Find mocks base method.
func (m *MockStorageInterface) Find(pid uint64) (*models.Storage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", pid)
	ret0, _ := ret[0].(*models.Storage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockStorageInterfaceMockRecorder) Find(pid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockStorageInterface)(nil).Find), pid)
}

// SaveStorage mocks base method.
func (m *MockStorageInterface) SaveStorage(data models.Storage) (*models.Storage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveStorage", data)
	ret0, _ := ret[0].(*models.Storage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveStorage indicates an expected call of SaveStorage.
func (mr *MockStorageInterfaceMockRecorder) SaveStorage(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveStorage", reflect.TypeOf((*MockStorageInterface)(nil).SaveStorage), data)
}

// Update mocks base method.
func (m *MockStorageInterface) Update(data models.Storage) (*models.Storage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", data)
	ret0, _ := ret[0].(*models.Storage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockStorageInterfaceMockRecorder) Update(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStorageInterface)(nil).Update), data)
}
