// Code generated by MockGen. DO NOT EDIT.
// Source: api/models/Subscription_interface.go

// Package mockdb is a generated GoMock package.
package mockdb

import (
	models "01cloud-api/api/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "github.com/jinzhu/gorm"
)

// MockSubscriptionInterface is a mock of SubscriptionInterface interface.
type MockSubscriptionInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionInterfaceMockRecorder
}

// MockSubscriptionInterfaceMockRecorder is the mock recorder for MockSubscriptionInterface.
type MockSubscriptionInterfaceMockRecorder struct {
	mock *MockSubscriptionInterface
}

// NewMockSubscriptionInterface creates a new mock instance.
func NewMockSubscriptionInterface(ctrl *gomock.Controller) *MockSubscriptionInterface {
	mock := &MockSubscriptionInterface{ctrl: ctrl}
	mock.recorder = &MockSubscriptionInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionInterface) EXPECT() *MockSubscriptionInterfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSubscriptionInterface) Delete(db *gorm.DB, uid uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", db, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockSubscriptionInterfaceMockRecorder) Delete(db, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSubscriptionInterface)(nil).Delete), db, uid)
}

// Find mocks base method.
func (m *MockSubscriptionInterface) Find(db *gorm.DB, pid uint64) (*models.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", db, pid)
	ret0, _ := ret[0].(*models.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockSubscriptionInterfaceMockRecorder) Find(db, pid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockSubscriptionInterface)(nil).Find), db, pid)
}

// FindAll mocks base method.
func (m *MockSubscriptionInterface) FindAll(db *gorm.DB, orgid uint64) (*[]models.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", db, orgid)
	ret0, _ := ret[0].(*[]models.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockSubscriptionInterfaceMockRecorder) FindAll(db, orgid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockSubscriptionInterface)(nil).FindAll), db, orgid)
}

// FindAllByUserID mocks base method.
func (m *MockSubscriptionInterface) FindAllByUserID(db *gorm.DB, uid uint64) (*[]models.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByUserID", db, uid)
	ret0, _ := ret[0].(*[]models.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByUserID indicates an expected call of FindAllByUserID.
func (mr *MockSubscriptionInterfaceMockRecorder) FindAllByUserID(db, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByUserID", reflect.TypeOf((*MockSubscriptionInterface)(nil).FindAllByUserID), db, uid)
}

// FindByUserID mocks base method.
func (m *MockSubscriptionInterface) FindByUserID(db *gorm.DB, uid uint64) (*[]models.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", db, uid)
	ret0, _ := ret[0].(*[]models.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockSubscriptionInterfaceMockRecorder) FindByUserID(db, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockSubscriptionInterface)(nil).FindByUserID), db, uid)
}

// Save mocks base method.
func (m *MockSubscriptionInterface) Save(db *gorm.DB, data models.Subscription) (*models.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", db, data)
	ret0, _ := ret[0].(*models.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockSubscriptionInterfaceMockRecorder) Save(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSubscriptionInterface)(nil).Save), db, data)
}

// Update mocks base method.
func (m *MockSubscriptionInterface) Update(db *gorm.DB, data models.Subscription) (*models.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", db, data)
	ret0, _ := ret[0].(*models.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSubscriptionInterfaceMockRecorder) Update(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSubscriptionInterface)(nil).Update), db, data)
}
