// Code generated by MockGen. DO NOT EDIT.
// Source: api/models/UserRole_interface.go

// Package mockdb is a generated GoMock package.
package mockdb

import (
	models "01cloud-api/api/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "github.com/jinzhu/gorm"
)

// MockUserRoleInterface is a mock of UserRoleInterface interface.
type MockUserRoleInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserRoleInterfaceMockRecorder
}

// MockUserRoleInterfaceMockRecorder is the mock recorder for MockUserRoleInterface.
type MockUserRoleInterfaceMockRecorder struct {
	mock *MockUserRoleInterface
}

// NewMockUserRoleInterface creates a new mock instance.
func NewMockUserRoleInterface(ctrl *gomock.Controller) *MockUserRoleInterface {
	mock := &MockUserRoleInterface{ctrl: ctrl}
	mock.recorder = &MockUserRoleInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRoleInterface) EXPECT() *MockUserRoleInterfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUserRoleInterface) Delete(db *gorm.DB, uid uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", db, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRoleInterfaceMockRecorder) Delete(db, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRoleInterface)(nil).Delete), db, uid)
}

// Find mocks base method.
func (m *MockUserRoleInterface) Find(db *gorm.DB, pid uint64) (*models.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", db, pid)
	ret0, _ := ret[0].(*models.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockUserRoleInterfaceMockRecorder) Find(db, pid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUserRoleInterface)(nil).Find), db, pid)
}

// FindAll mocks base method.
func (m *MockUserRoleInterface) FindAll(db *gorm.DB) (*[]models.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", db)
	ret0, _ := ret[0].(*[]models.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockUserRoleInterfaceMockRecorder) FindAll(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockUserRoleInterface)(nil).FindAll), db)
}

// Save mocks base method.
func (m *MockUserRoleInterface) Save(db *gorm.DB, data *models.UserRole) (*models.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", db, data)
	ret0, _ := ret[0].(*models.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockUserRoleInterfaceMockRecorder) Save(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserRoleInterface)(nil).Save), db, data)
}

// Update mocks base method.
func (m *MockUserRoleInterface) Update(db *gorm.DB, data *models.UserRole) (*models.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", db, data)
	ret0, _ := ret[0].(*models.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserRoleInterfaceMockRecorder) Update(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRoleInterface)(nil).Update), db, data)
}
