// Code generated by MockGen. DO NOT EDIT.
// Source: api/models/UserInvite_Interface.go

// Package mockdb is a generated GoMock package.
package mockdb

import (
	models "01cloud-api/api/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "github.com/jinzhu/gorm"
)

// MockUserInviteInterface is a mock of UserInviteInterface interface.
type MockUserInviteInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserInviteInterfaceMockRecorder
}

// MockUserInviteInterfaceMockRecorder is the mock recorder for MockUserInviteInterface.
type MockUserInviteInterfaceMockRecorder struct {
	mock *MockUserInviteInterface
}

// NewMockUserInviteInterface creates a new mock instance.
func NewMockUserInviteInterface(ctrl *gomock.Controller) *MockUserInviteInterface {
	mock := &MockUserInviteInterface{ctrl: ctrl}
	mock.recorder = &MockUserInviteInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserInviteInterface) EXPECT() *MockUserInviteInterfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUserInviteInterface) Delete(db *gorm.DB, uid uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", db, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockUserInviteInterfaceMockRecorder) Delete(db, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserInviteInterface)(nil).Delete), db, uid)
}

// Find mocks base method.
func (m *MockUserInviteInterface) Find(db *gorm.DB, pid uint64) (*models.UserInvite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", db, pid)
	ret0, _ := ret[0].(*models.UserInvite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockUserInviteInterfaceMockRecorder) Find(db, pid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUserInviteInterface)(nil).Find), db, pid)
}

// FindAll mocks base method.
func (m *MockUserInviteInterface) FindAll(db *gorm.DB) (*[]models.UserInvite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", db)
	ret0, _ := ret[0].(*[]models.UserInvite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockUserInviteInterfaceMockRecorder) FindAll(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockUserInviteInterface)(nil).FindAll), db)
}

// FindByEmail mocks base method.
func (m *MockUserInviteInterface) FindByEmail(db *gorm.DB, email string) (*models.UserInvite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", db, email)
	ret0, _ := ret[0].(*models.UserInvite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockUserInviteInterfaceMockRecorder) FindByEmail(db, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockUserInviteInterface)(nil).FindByEmail), db, email)
}

// FindByToken mocks base method.
func (m *MockUserInviteInterface) FindByToken(db *gorm.DB, token string) (*models.UserInvite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByToken", db, token)
	ret0, _ := ret[0].(*models.UserInvite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByToken indicates an expected call of FindByToken.
func (mr *MockUserInviteInterfaceMockRecorder) FindByToken(db, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByToken", reflect.TypeOf((*MockUserInviteInterface)(nil).FindByToken), db, token)
}

// Save mocks base method.
func (m *MockUserInviteInterface) Save(db *gorm.DB, data models.UserInvite) (*models.UserInvite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", db, data)
	ret0, _ := ret[0].(*models.UserInvite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockUserInviteInterfaceMockRecorder) Save(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserInviteInterface)(nil).Save), db, data)
}

// Update mocks base method.
func (m *MockUserInviteInterface) Update(db *gorm.DB, data models.UserInvite) (*models.UserInvite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", db, data)
	ret0, _ := ret[0].(*models.UserInvite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserInviteInterfaceMockRecorder) Update(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserInviteInterface)(nil).Update), db, data)
}
