// Code generated by MockGen. DO NOT EDIT.
// Source: api/models/User_Interface.go

// Package mockdb is a generated GoMock package.
package mockdb

import (
	models "01cloud-api/api/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "github.com/jinzhu/gorm"
)

// MockUserInterface is a mock of UserInterface interface.
type MockUserInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserInterfaceMockRecorder
}

// MockUserInterfaceMockRecorder is the mock recorder for MockUserInterface.
type MockUserInterfaceMockRecorder struct {
	mock *MockUserInterface
}

// NewMockUserInterface creates a new mock instance.
func NewMockUserInterface(ctrl *gomock.Controller) *MockUserInterface {
	mock := &MockUserInterface{ctrl: ctrl}
	mock.recorder = &MockUserInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserInterface) EXPECT() *MockUserInterfaceMockRecorder {
	return m.recorder
}

// DeleteAUser mocks base method.
func (m *MockUserInterface) DeleteAUser(db *gorm.DB, uid uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAUser", db, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAUser indicates an expected call of DeleteAUser.
func (mr *MockUserInterfaceMockRecorder) DeleteAUser(db, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAUser", reflect.TypeOf((*MockUserInterface)(nil).DeleteAUser), db, uid)
}

// FindAllUsers mocks base method.
func (m *MockUserInterface) FindAllUsers(db *gorm.DB) (*[]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllUsers", db)
	ret0, _ := ret[0].(*[]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllUsers indicates an expected call of FindAllUsers.
func (mr *MockUserInterfaceMockRecorder) FindAllUsers(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllUsers", reflect.TypeOf((*MockUserInterface)(nil).FindAllUsers), db)
}

// FindAllUsersWithFilters mocks base method.
func (m *MockUserInterface) FindAllUsersWithFilters(db *gorm.DB, page, size uint64, q, sortColumn, sortDirection string) (*[]models.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllUsersWithFilters", db, page, size, q, sortColumn, sortDirection)
	ret0, _ := ret[0].(*[]models.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAllUsersWithFilters indicates an expected call of FindAllUsersWithFilters.
func (mr *MockUserInterfaceMockRecorder) FindAllUsersWithFilters(db, page, size, q, sortColumn, sortDirection interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllUsersWithFilters", reflect.TypeOf((*MockUserInterface)(nil).FindAllUsersWithFilters), db, page, size, q, sortColumn, sortDirection)
}

// FindUserByEmail mocks base method.
func (m *MockUserInterface) FindUserByEmail(db *gorm.DB, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByEmail", db, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByEmail indicates an expected call of FindUserByEmail.
func (mr *MockUserInterfaceMockRecorder) FindUserByEmail(db, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByEmail", reflect.TypeOf((*MockUserInterface)(nil).FindUserByEmail), db, email)
}

// FindUserByID mocks base method.
func (m *MockUserInterface) FindUserByID(db *gorm.DB, uid uint) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByID", db, uid)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByID indicates an expected call of FindUserByID.
func (mr *MockUserInterfaceMockRecorder) FindUserByID(db, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByID", reflect.TypeOf((*MockUserInterface)(nil).FindUserByID), db, uid)
}

// GetActiveSessionByUserId mocks base method.
func (m *MockUserInterface) GetActiveSessionByUserId(db *gorm.DB, userid uint) (*[]models.Session, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveSessionByUserId", db, userid)
	ret0, _ := ret[0].(*[]models.Session)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetActiveSessionByUserId indicates an expected call of GetActiveSessionByUserId.
func (mr *MockUserInterfaceMockRecorder) GetActiveSessionByUserId(db, userid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveSessionByUserId", reflect.TypeOf((*MockUserInterface)(nil).GetActiveSessionByUserId), db, userid)
}

// GetAllSessionByUserId mocks base method.
func (m *MockUserInterface) GetAllSessionByUserId(db *gorm.DB, userid uint, limit, offset int) (*[]models.Session, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSessionByUserId", db, userid, limit, offset)
	ret0, _ := ret[0].(*[]models.Session)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllSessionByUserId indicates an expected call of GetAllSessionByUserId.
func (mr *MockUserInterfaceMockRecorder) GetAllSessionByUserId(db, userid, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSessionByUserId", reflect.TypeOf((*MockUserInterface)(nil).GetAllSessionByUserId), db, userid, limit, offset)
}

// GetSessionById mocks base method.
func (m *MockUserInterface) GetSessionById(db *gorm.DB, uid uint) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionById", db, uid)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionById indicates an expected call of GetSessionById.
func (mr *MockUserInterfaceMockRecorder) GetSessionById(db, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionById", reflect.TypeOf((*MockUserInterface)(nil).GetSessionById), db, uid)
}

// SaveSession mocks base method.
func (m *MockUserInterface) SaveSession(db *gorm.DB, data *models.Session) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSession", db, data)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveSession indicates an expected call of SaveSession.
func (mr *MockUserInterfaceMockRecorder) SaveSession(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSession", reflect.TypeOf((*MockUserInterface)(nil).SaveSession), db, data)
}

// SaveUser mocks base method.
func (m *MockUserInterface) SaveUser(db *gorm.DB, data *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", db, data)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveUser indicates an expected call of SaveUser.
func (mr *MockUserInterfaceMockRecorder) SaveUser(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockUserInterface)(nil).SaveUser), db, data)
}

// UpdateAUser mocks base method.
func (m *MockUserInterface) UpdateAUser(db *gorm.DB, uid uint, data *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAUser", db, uid, data)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAUser indicates an expected call of UpdateAUser.
func (mr *MockUserInterfaceMockRecorder) UpdateAUser(db, uid, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAUser", reflect.TypeOf((*MockUserInterface)(nil).UpdateAUser), db, uid, data)
}

// UpdatePassword mocks base method.
func (m *MockUserInterface) UpdatePassword(db *gorm.DB, u *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", db, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUserInterfaceMockRecorder) UpdatePassword(db, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserInterface)(nil).UpdatePassword), db, u)
}

// UpdateSession mocks base method.
func (m *MockUserInterface) UpdateSession(db *gorm.DB, data models.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", db, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockUserInterfaceMockRecorder) UpdateSession(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockUserInterface)(nil).UpdateSession), db, data)
}

// UpdateUserQuota mocks base method.
func (m *MockUserInterface) UpdateUserQuota(db *gorm.DB, data *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserQuota", db, data)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserQuota indicates an expected call of UpdateUserQuota.
func (mr *MockUserInterfaceMockRecorder) UpdateUserQuota(db, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserQuota", reflect.TypeOf((*MockUserInterface)(nil).UpdateUserQuota), db, data)
}

// VerifyEmail mocks base method.
func (m *MockUserInterface) VerifyEmail(db *gorm.DB, uid uint) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmail", db, uid)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyEmail indicates an expected call of VerifyEmail.
func (mr *MockUserInterfaceMockRecorder) VerifyEmail(db, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmail", reflect.TypeOf((*MockUserInterface)(nil).VerifyEmail), db, uid)
}
